server:
  port: 8888
  max-http-header-size: 1048576


swagger:
  enable: true

#spring:
#  redis:
#    password: admin
#    jedis:
#      pool:
#        #最大连接数
#        max-active: 1024
#        #最大阻塞等待时间(负数表示没限制)
#        max-wait: 200
#        #最大空闲
#        max-idle: 300
#        #最小空闲
#        min-idle: 10
#    sentinel:
#      master: mymaster
#      nodes: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381
#       - 192.168.2.110:26379
#       - 192.168.2.110:26380
#       - 192.168.2.110:26381

my:
  redis:
    port: 6379
    password: 123456
    database: 0
    hostName: 127.0.0.1

